/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "贪狼武曲",
  "description": "建站指南",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/cat.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "vuePress博客搭建指南",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-5aa831a8",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "安装初始化",
          "slug": "安装初始化"
        },
        {
          "level": 2,
          "title": "核心配置",
          "slug": "核心配置"
        },
        {
          "level": 2,
          "title": "导航栏配置",
          "slug": "导航栏配置"
        },
        {
          "level": 2,
          "title": "侧边栏配置",
          "slug": "侧边栏配置"
        },
        {
          "level": 2,
          "title": "静态资源配置",
          "slug": "静态资源配置"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/cat.jpg",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-9afdd4d6",
      "path": "/"
    },
    {
      "title": "vuePress博客搭建指南",
      "frontmatter": {},
      "regularPath": "/guide/notes/one.html",
      "relativePath": "guide/notes/one.md",
      "key": "v-cb9b8f28",
      "path": "/guide/notes/one.html",
      "headers": [
        {
          "level": 2,
          "title": "安装初始化",
          "slug": "安装初始化"
        },
        {
          "level": 2,
          "title": "核心配置",
          "slug": "核心配置"
        },
        {
          "level": 2,
          "title": "导航栏配置",
          "slug": "导航栏配置"
        },
        {
          "level": 2,
          "title": "侧边栏配置",
          "slug": "侧边栏配置"
        },
        {
          "level": 2,
          "title": "静态资源配置",
          "slug": "静态资源配置"
        }
      ]
    },
    {
      "title": "博客搭建下的一级标题",
      "frontmatter": {},
      "regularPath": "/guide/notes/two.html",
      "relativePath": "guide/notes/two.md",
      "key": "v-304633a8",
      "path": "/guide/notes/two.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "建站指南",
        "link": "/guide/"
      },
      {
        "text": "面试宝典",
        "items": [
          {
            "text": "初级开发篇",
            "link": "/interview/junior/"
          },
          {
            "text": "中高进阶篇",
            "link": "/interview/advanced/"
          }
        ]
      },
      {
        "text": "工具箱",
        "items": [
          {
            "text": "在线编辑",
            "items": [
              {
                "text": "图片压缩",
                "link": "https://tinypng.com/"
              }
            ]
          },
          {
            "text": "在线服务",
            "items": [
              {
                "text": "阿里云",
                "link": "https://www.aliyun.com/"
              },
              {
                "text": "腾讯云",
                "link": "https://cloud.tencent.com/"
              }
            ]
          },
          {
            "text": "博客指南",
            "items": [
              {
                "text": "掘金",
                "link": "https://juejin.im/"
              },
              {
                "text": "CSDN",
                "link": "https://blog.csdn.net/"
              }
            ]
          }
        ]
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "博客搭建",
          "collapsable": true,
          "children": [
            "/guide/notes/one"
          ]
        },
        {
          "title": "第二个导航",
          "collapsable": true,
          "children": [
            "/guide/notes/two"
          ]
        }
      ]
    },
    "sidebarDepth": 2,
    "lastUpdated": "Last Updated",
    "searchMaxSuggestoins": 10,
    "serviceWorker": {
      "updatePopup": {
        "message": "有新的内容.",
        "buttonText": "更新"
      }
    },
    "editLinks": true,
    "editLinkText": "在 GitHub 上编辑此页 ！"
  }
}